quotes = [
    "You don’t have to be extreme, just consistent.",
    "Strong is not just physical – it’s mindset.",
    "Small steps every day lead to big results.",
    "Your only limit is you.",
    "Push yourself because no one else is going to do it for you.",
    "Discipline is doing it even when you don’t feel like it.",
    "One workout at a time. One day at a time.",
    "Fall in love with the process.",
    "Progress, not perfection.",
    "It doesn’t get easier – you get stronger.",
    "Results happen over time, not overnight.",
    "Your body can stand almost anything. It’s your mind you have to convince.",
    "Don’t wish for it. Work for it.",
    "Make yourself proud.",
    "Strive for progress, not perfection.",
    "The hard part isn’t getting your body in shape. The hard part is getting your mind in shape.",
    "Be stronger than your strongest excuse.",
    "It’s a slow process, but quitting won’t speed it up.",
    "You’re one workout away from a better mood.",
    "Fitness is not about being better than someone else. It’s about being better than you used to be.",
    "Consistency beats motivation.",
    "When you feel like quitting, think about why you started.",
    "Nothing changes if nothing changes.",
    "A little progress each day adds up to big results.",
    "Wake up. Work out. Show up.",
    "The only bad workout is the one that didn’t happen.",
    "Some days you won’t feel like it – do it anyway.",
    "Energy grows with motion.",
    "Be patient. Stay focused. Trust the process.",
    "This is your time. Make it count."
]

exercise_icons = [
    "dashboard_img/workout_icon_1.svg",
    "dashboard_img/workout_icon_2.svg",
    "dashboard_img/workout_icon_3.svg",
    "dashboard_img/workout_icon_4.svg",
    "dashboard_img/workout_icon_5.svg",
    "dashboard_img/workout_icon_6.svg"
]